export const SOLDIER_CONSTANTS = {
  // Leveling
  MAX_LEVEL: 12,
  EXPERIENCE_RATE: 1,
  EXPERIENCE_PER_LEVEL: 100,
  EXPERIENCE_STEP: 3,
  EXPERIENCE_UNIT: 50,
  
  // Gold
  GOLD_RATE: 0.035,
  GOLD_STEP: 0.5,
  
  // Movement
  STAND_DISTANCE: 30,
  HIT_DISTANCE: 100,
  RANGE_OFFSET: 150,
  ROTATION_SPEED: 0.1,
  WALK_ROTATION_SPEED: 0.05,
  
  // Rotation
  ANGLE_THRESHOLD: 1,
  ANGLE_WRAP_THRESHOLD: 180,
  FULL_CIRCLE: 360,
  RADIANS_TO_DEGREES: 57.29578,
  
  // World positioning
  WORLD_Y_OFFSET: 15,
  TILE_ROW_MULTIPLIER: 32
} as const;
